-- 코드를 입력하세요
SELECT
    date_format(SALES_DATE, "%Y-%m-%d") SALES_DATE,
    PRODUCT_ID,
    USER_ID,
    SUM(SALES_AMOUNT) SALES_AMOUNT
FROM (SELECT
    SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT
FROM
    ONLINE_SALE 
WHERE
    SALES_DATE BETWEEN '2022-03-01' AND '2022-03-31'
union all
SELECT
    SALES_DATE, PRODUCT_ID, NULL, SALES_AMOUNT
FROM
    OFFLINE_SALE
WHERE
    SALES_DATE BETWEEN '2022-03-01' AND '2022-03-31') u
GROUP BY
    PRODUCT_ID
ORDER BY
    SALES_DATE, PRODUCT_ID, USER_ID;